COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS :=
CXXFLAGS += -std=gnu++17 -frtti

ESPRESSIO_SECURITY_VERSION_MAJOR := 0
ESPRESSIO_SECURITY_VERSION_MINOR := 4
ESPRESSIO_SECURITY_VERSION_PATCH := 2
ESPRESSIO_SECURITY_VERSION := 0.4.2
