COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS :=
CXXFLAGS += -std=gnu++17

ESPRESSIO_SECURITY_VERSION_MAJOR := 0
ESPRESSIO_SECURITY_VERSION_MINOR := 2
ESPRESSIO_SECURITY_VERSION_PATCH := 0
ESPRESSIO_SECURITY_VERSION := 0.2.0
