cmake_minimum_required(VERSION 3.16)
project(ESPressioSecurityTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
add_executable(Security test_security.cpp)
target_include_directories(Security PRIVATE ../src)
add_executable(SecureTransportDecorator test_decorator.cpp)
target_include_directories(SecureTransportDecorator PRIVATE ../src)
enable_testing()
add_test(NAME Security COMMAND Security)
add_test(NAME SecureTransportDecorator COMMAND SecureTransportDecorator)
