#include <cassert>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <vector>
#include "ESPressio_Security.hpp"
using namespace ESPressio::Security;
class TinyCipher final:public IAeadCipher{public:AeadAlgorithm Algorithm()const noexcept override{return AeadAlgorithm::TestOnly;}const char*Name()const noexcept override{return"TEST";}std::size_t KeySize()const noexcept override{return16;}std::size_t NonceSize()const noexcept override{return12;}std::size_t TagSize()const noexcept override{return16;}bool Seal(const uint8_t*k,std::size_t ks,const uint8_t*n,std::size_t ns,const uint8_t*a,std::size_t as,const uint8_t*p,std::size_t ps,std::vector<uint8_t>&c,std::vector<uint8_t>&t)override{if(ks!=16||ns!=12)return false;c.assign(p,p+ps);for(std::size_t i=0;i<ps;++i)c[i]^=k[i%ks]^n[i%ns];uint8_t x=0;for(std::size_t i=0;i<as;++i)x^=a[i];for(auto b:c)x^=b;for(std::size_t i=0;i<ks;++i)x^=k[i];t.assign(16,x);return true;}bool Open(const uint8_t*k,std::size_t ks,const uint8_t*n,std::size_t ns,const uint8_t*a,std::size_t as,const uint8_t*c,std::size_t cs,const uint8_t*t,std::size_t ts,std::vector<uint8_t>&p)override{if(ks!=16||ns!=12||ts!=16)return false;uint8_t x=0;for(std::size_t i=0;i<as;++i)x^=a[i];for(std::size_t i=0;i<cs;++i)x^=c[i];for(std::size_t i=0;i<ks;++i)x^=k[i];uint8_t d=0;for(std::size_t i=0;i<ts;++i)d|=t[i]^x;if(d)return false;p.assign(c,c+cs);for(std::size_t i=0;i<cs;++i)p[i]^=k[i%ks]^n[i%ns];return true;}};
class Random final:public IRandomSource{public:bool Fill(uint8_t*o,std::size_t s)override{for(std::size_t i=0;i<s;++i)o[i]=static_cast<uint8_t>(++n);return true;}uint8_t n=0;};
class LoopbackCarrier final:public ITransportSecurityCarrier{public:bool Send(uint8_t p,const uint8_t*d,std::size_t s)override{last.assign(d,d+s);if(rx)rx(p,last.data(),last.size());return true;}void SetReceiver(Receiver r)override{rx=std::move(r);}Receiver rx;std::vector<uint8_t>last;};
int main(){TinyCipher cipher;AeadCipherRegistry registry;registry.Register(cipher);StaticKeyProvider keys;uint8_t key[16]={1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};keys.Add(1,AeadAlgorithm::TestOnly,key,16);Random random;TransportSecurityConfig cfg;cfg.Policy=TransportSecurityPolicy::Required;cfg.OutboundAlgorithm=AeadAlgorithm::TestOnly;cfg.OutboundKeyID=1;cfg.SenderID=77;TransportSecurity security(registry,keys,random,cfg);LoopbackCarrier carrier;SecureTransportDecorator secure(carrier,security);bool received=false;secure.SetReceiver([&](uint8_t protocol,const UnprotectedPayload&payload){received=true;assert(protocol==9);assert(payload.Protected);assert(std::string(payload.Data.begin(),payload.Data.end())=="hello");});SecurityResult result;assert(secure.Send(9,reinterpret_cast<const uint8_t*>("hello"),5,&result));assert(result.Success&&result.Protected&&received);assert(TransportSecurity::LooksProtected(carrier.last.data(),carrier.last.size()));std::cout<<"Secure transport decorator test passed\n";}
